import { useForm } from '@inertiajs/react';
import { FormEvent } from 'react';
import { PageHeader } from '@/components/page-header';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { formatRupiah } from '@/lib/formatters';

type Settings = { store_name: string; store_phone: string; admin_whatsapp: string; store_address: string; customer_order_template: string; admin_order_template: string; public_order_enabled: boolean; minimum_pickup_days: number; opening_time: string; closing_time: string };
type Props = { settings: Settings; sizes: Array<{ id: number; name: string; base_price: string; is_active: boolean }>; shapes: Array<{ id: number; name: string; price_adjustment: string; is_active: boolean }>; flavors: Array<{ id: number; name: string; type: string; price_adjustment: string; is_active: boolean }>; items: Array<{ id: number; name: string; price: string; unit: string; is_active: boolean }> };
export function SettingsPageContent({ settings, sizes, shapes, flavors, items }: Props) { const form = useForm(settings); const submit=(e:FormEvent)=>{e.preventDefault();form.put('/admin/settings');}; return <div className="space-y-6 p-4 md:p-6"><PageHeader title="Pengaturan" description="Kelola toko, template notifikasi, dan master harga."/><form onSubmit={submit}><Card><CardHeader><CardTitle>Profil dan notifikasi</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-2"><input value={form.data.store_name} onChange={e=>form.setData('store_name',e.target.value)} placeholder="Nama toko"/><input value={form.data.store_phone} onChange={e=>form.setData('store_phone',e.target.value)} placeholder="Telepon toko"/><input value={form.data.admin_whatsapp} onChange={e=>form.setData('admin_whatsapp',e.target.value)} placeholder="WhatsApp admin"/><input type="number" value={form.data.minimum_pickup_days} onChange={e=>form.setData('minimum_pickup_days',Number(e.target.value))} placeholder="Minimum hari pickup"/><textarea className="md:col-span-2" value={form.data.customer_order_template} onChange={e=>form.setData('customer_order_template',e.target.value)}/><textarea className="md:col-span-2" value={form.data.admin_order_template} onChange={e=>form.setData('admin_order_template',e.target.value)}/><Button disabled={form.processing} className="w-fit">Simpan pengaturan</Button></CardContent></Card></form><div className="grid gap-6 xl:grid-cols-2"><Catalog title="Ukuran kue" rows={sizes.map(x=>[x.name,formatRupiah(Number(x.base_price)),x.is_active])}/><Catalog title="Bentuk kue" rows={shapes.map(x=>[x.name,formatRupiah(Number(x.price_adjustment)),x.is_active])}/><Catalog title="Rasa" rows={flavors.map(x=>[`${x.name} (${x.type})`,formatRupiah(Number(x.price_adjustment)),x.is_active])}/><Catalog title="Item tambahan" rows={items.map(x=>[x.name,`${formatRupiah(Number(x.price))} / ${x.unit}`,x.is_active])}/></div></div>; }
function Catalog({ title, rows }: { title: string; rows: Array<[string,string,boolean]> }) { return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent className="space-y-2">{rows.map(([name, price, active])=><div key={name} className="flex justify-between rounded border p-3"><span>{name}</span><span className="text-muted-foreground">{price} · {active?'Aktif':'Nonaktif'}</span></div>)}</CardContent></Card>; }
