services:
  app:
    image: ghcr.io/sandemoit/digital-store:dev
    container_name: sanstore_dev
    env_file:
      - stack.env
    expose:
      - "8080"
    volumes:
      - /opt/sandemo/apps/sanstore/storage:/var/www/html/storage
    restart: unless-stopped
    networks:
      - sandemo-network

networks:
  sandemo-network:
    external: true